[package]
name = "yeight-http"
version = "0.1.0"
authors = ["Skyler van Boheemen"]
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
routerify = "2.1.0"
hyper = "0.14.9"
tokio = { version ="1.7.0", features = ["full"] }